# Link the Microsoft C runtime into the exe, so it runs on PCs without the
# Visual C++ Redistributable (VCRUNTIME140.dll was missing on a site PC).
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
